[project]
name = "app"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "art>=6.5",
    "functions-framework>=3.9.2",
    "googletrans==4.0.0rc1",
]
